/**
 * Drop turns whose text is not authored by the user but was injected by the
 * agent runtime, a skill loader, a hook, or a context-compaction step.
 *
 * These are silent contaminators of `user_corrections` and `prompt_templates`:
 * the messages live on user turns but carry no user intent. Keeping them
 * inflates the top-N for kinds like `style` / `scope` and clogs first-prompt
 * templates with skill bodies and continuation preambles.
 *
 * Match on stable, generic prefixes only. Do NOT pattern-match individual
 * skill names, project names, or specific user content — that would couple
 * the corpus extractor to a particular consumer.
 */

const INJECTED_PREFIXES: readonly RegExp[] = [
  // Skill loader: every Claude Code skill body is fed back into the next user
  // turn with this exact preamble. Generic across all skills.
  /^Base directory for this skill:\s*\S/,
  // Claude Code auto-compaction handoff turn.
  /^This session is being continued from a previous (?:session|conver(?:sation))/,
  // Claude Code Stop hook feedback echoed as a user turn.
  /^Stop hook feedback:/,
  // Anthropic system-reminder envelope (delivered as a user turn).
  /^<system-reminder>/,
  // Slash-command echo with optional command-message / command-args / stdout
  // siblings, prefixed by the local-commands caveat block.
  /^<command-name>/,
  /^Caveat: The messages below were generated by the user while running local commands/,
];

/**
 * Returns true if `text` looks like agent/system-injected content rather than
 * a real user turn. Trims leading whitespace before matching.
 */
export function isInjectedNoise(text: string | null | undefined): boolean {
  if (!text) return false;
  const t = text.replace(/^\s+/, "");
  if (!t) return false;
  for (const re of INJECTED_PREFIXES) {
    if (re.test(t)) return true;
  }
  return false;
}
