/**
 * Stable prefixes for turns that are injected by an agent runtime, skill
 * loader, approval reviewer, hook, or context-compaction step.
 *
 * Keep these generic. Never add a project name, skill name, or user-specific
 * phrase: the list is shared by extractors and search filters.
 */
export const INJECTED_TEXT_PREFIXES = [
  // Claude Code skill loader.
  "Base directory for this skill:",
  // Claude Code auto-compaction handoff.
  "This session is being continued from a previous ",
  // Claude Code Stop hook feedback echoed as a user turn.
  "Stop hook feedback:",
  // Anthropic system-reminder envelope.
  "<system-reminder>",
  // Slash-command echo and its local-command caveat block.
  "<command-name>",
  "Caveat: The messages below were generated by the user while running local commands",
  // Codex runtime instruction, environment, plugin, and loaded-skill envelopes.
  "# AGENTS.md instructions",
  "<environment_context>",
  "<recommended_plugins>",
  "<plugin_info",
  "<manually_attached_skills>",
  "<skill>",
  "<agent_transcripts>",
  "<subagent_notification>",
  "<turn_aborted>",
  "<timestamp>",
  // Runtime hook and local-command envelopes.
  "<hooks_context",
  "<user_shell_command>",
  "<cursor_commands>",
  // Codex automatic action-review transcript and incremental deltas.
  "The following is the Codex agent history",
] as const;

/**
 * Returns true if `text` looks like agent/system-injected content rather than
 * a real user turn. Trims leading whitespace before matching.
 */
export function isInjectedNoise(text: string | null | undefined): boolean {
  if (!text) return false;
  const t = text.replace(/^\s+/, "");
  if (!t) return false;
  return INJECTED_TEXT_PREFIXES.some((prefix) => t.startsWith(prefix));
}
